//! Resource definition macros
//!
//! This module provides declarative macros for unified resource type definitions.
//! The goal is to define all resource metadata in one place and auto-generate
//! repetitive code across the codebase.
//!
//! # Design Principles
//! - Single source of truth for resource definitions
//! - Compile-time exhaustiveness checking
//! - Backward compatible with existing code
//! - Does not break list/watch architecture

/// Capacity tier constants for resource EventStore sizing.
/// Used in `define_resources!` via the `default_capacity` field.
pub const CAPACITY_SMALL: u32 = 50;
pub const CAPACITY_NORMAL: u32 = 200;
pub const CAPACITY_LARGE: u32 = 1000;

/// Main macro for defining all resource types in a unified way.
///
/// This macro generates:
/// - `ResourceKindInfo` struct with metadata for each resource
/// - `ALL_RESOURCE_INFOS` static array containing all resource metadata
/// - Helper functions for resource type lookups
///
/// # Example
/// ```ignore
/// define_resources! {
///     GatewayClass {
///         enum_value: 1,
///         kind_name: "GatewayClass",
///         kind_aliases: ["gatewayclass"],
///         cache_field: gateway_classes,
///         capacity_field: gateway_classes_capacity,
///         default_capacity: small,
///         cluster_scoped: true,
///         is_base_conf: true,
///     },
///     // ... more resources
/// }
/// ```
#[macro_export]
macro_rules! define_resources {
    (
        $(
            $variant:ident {
                enum_value: $enum_val:expr,
                kind_name: $kind_name:literal,
                kind_aliases: [$($alias:literal),* $(,)?],
                cache_field: $cache_field:ident,
                capacity_field: $cap_field:ident,
                default_capacity: $cap_default:ident,
                $(cluster_scoped: $cluster:literal,)?
                $(is_base_conf: $base:literal,)?
                $(in_registry: $in_reg:literal,)?
            }
        ),* $(,)?
    ) => {
        /// Metadata information for a resource kind (generated by macro)
        #[derive(Debug, Clone, Copy)]
        pub struct ResourceKindInfo {
            /// The ResourceKind enum variant value
            pub kind: $crate::types::ResourceKind,
            /// Human-readable kind name (e.g., "GatewayClass")
            pub kind_name: &'static str,
            /// Cache field name in ConfigServer/ConfigClient
            pub cache_field_name: &'static str,
            /// Capacity config field name
            pub capacity_field_name: &'static str,
            /// Default EventStore capacity (from capacity tier: small/normal/large)
            pub default_capacity: u32,
            /// Whether this is a cluster-scoped resource
            pub cluster_scoped: bool,
            /// Whether this is a base configuration resource
            pub is_base_conf: bool,
            /// Whether this resource should be included in the resource registry
            /// (used for cache status checking, etc.)
            pub in_registry: bool,
        }

        /// Static array of all resource kind metadata
        pub static ALL_RESOURCE_INFOS: &[ResourceKindInfo] = &[
            $(
                ResourceKindInfo {
                    kind: $crate::types::ResourceKind::$variant,
                    kind_name: $kind_name,
                    cache_field_name: stringify!($cache_field),
                    capacity_field_name: stringify!($cap_field),
                    default_capacity: $crate::define_resources!(@capacity $cap_default),
                    cluster_scoped: $crate::define_resources!(@default_bool $($cluster)?),
                    is_base_conf: $crate::define_resources!(@default_bool $($base)?),
                    in_registry: $crate::define_resources!(@default_true $($in_reg)?),
                },
            )*
        ];

        /// Get ResourceKind from kind name string (case-insensitive)
        /// This is a generated alternative to ResourceKind::from_kind_name
        pub fn resource_kind_from_name(name: &str) -> Option<$crate::types::ResourceKind> {
            let lower = name.to_lowercase();
            match lower.as_str() {
                $(
                    $kind_name => Some($crate::types::ResourceKind::$variant),
                    $($alias => Some($crate::types::ResourceKind::$variant),)*
                )*
                _ => None,
            }
        }

        /// Get ResourceKindInfo by ResourceKind
        pub fn get_resource_info(kind: $crate::types::ResourceKind) -> Option<&'static ResourceKindInfo> {
            ALL_RESOURCE_INFOS.iter().find(|info| info.kind == kind)
        }

        /// Get all resource kind names (for registry compatibility)
        pub fn all_resource_kind_names() -> Vec<&'static str> {
            ALL_RESOURCE_INFOS.iter().map(|info| info.cache_field_name).collect()
        }

        /// Get resource names that should be included in the registry
        /// (excludes resources like Secret that follow related resources)
        pub fn registry_resource_names() -> Vec<&'static str> {
            ALL_RESOURCE_INFOS
                .iter()
                .filter(|info| info.in_registry)
                .map(|info| info.cache_field_name)
                .collect()
        }

        /// Get ResourceKind from cache field name (e.g. "gateway_classes" -> GatewayClass)
        ///
        /// This is the reverse mapping of cache_field_name -> ResourceKind,
        /// used by ConfigClient to bridge between registry names and ResourceKind enum.
        pub fn resource_kind_from_cache_field(cache_field: &str) -> Option<$crate::types::ResourceKind> {
            match cache_field {
                $(
                    stringify!($cache_field) => Some($crate::types::ResourceKind::$variant),
                )*
                _ => None,
            }
        }

        /// Get base configuration resource names
        pub fn base_conf_kind_names() -> Vec<&'static str> {
            ALL_RESOURCE_INFOS
                .iter()
                .filter(|info| info.is_base_conf)
                .map(|info| info.cache_field_name)
                .collect()
        }

        /// Check if a ResourceKind is cluster-scoped
        pub fn is_kind_cluster_scoped(kind: $crate::types::ResourceKind) -> bool {
            get_resource_info(kind).map(|info| info.cluster_scoped).unwrap_or(false)
        }

        /// Get the default EventStore capacity for a resource kind by name.
        ///
        /// Accepts the PascalCase variant name used by spawn (e.g., "HTTPRoute"),
        /// the lowercase kind_name (e.g., "httproute"), or the cache_field_name
        /// (e.g., "routes"). Returns `None` if no match is found.
        pub fn default_capacity_for_kind(name: &str) -> Option<u32> {
            let lower = name.to_lowercase();
            $(
                if lower == stringify!($variant).to_lowercase()
                    || lower == $kind_name
                    || lower == stringify!($cache_field)
                {
                    return Some($crate::define_resources!(@capacity $cap_default));
                }
            )*
            None
        }

        /// Compile-time exhaustiveness check helper
        /// This ensures all ResourceKind variants are covered in the macro definition
        #[allow(dead_code)]
        const fn _exhaustive_check() {
            // This will cause a compile error if a ResourceKind variant is missing
            // from the define_resources! macro invocation
            const fn check(kind: $crate::types::ResourceKind) {
                match kind {
                    $crate::types::ResourceKind::Unspecified => {}
                    $($crate::types::ResourceKind::$variant => {})*
                }
            }
            // Trigger the check at compile time
            check($crate::types::ResourceKind::Unspecified);
        }
    };

    // Helper: map capacity tier identifier to constant
    (@capacity small) => { $crate::types::resource::macros::CAPACITY_SMALL };
    (@capacity normal) => { $crate::types::resource::macros::CAPACITY_NORMAL };
    (@capacity large) => { $crate::types::resource::macros::CAPACITY_LARGE };

    // Helper: default to false if not specified
    (@default_bool) => { false };
    (@default_bool $val:literal) => { $val };

    // Helper: default to true if not specified (for in_registry)
    (@default_true) => { true };
    (@default_true $val:literal) => { $val };
}

#[cfg(test)]
mod tests {
    // Tests will be added after resource_defs.rs is created
}
