apiVersion: v1
kind: Service
metadata:
  name: backend-a
  namespace: edgion-test
spec:
  ports:
    - name: http
      port: 30001
      protocol: TCP
      targetPort: 30001
  selector:
    app: edgion-test-server
