apiVersion: v1
kind: Service
metadata:
  name: diu-backend-canary
  namespace: edgion-default
spec:
  selector:
    app: edgion-test-server
  ports:
    - name: http
      port: 30002
      targetPort: 30002
      protocol: TCP
