apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: referencegrants.gateway.networking.k8s.io
  annotations:
    api-approved.kubernetes.io: "https://github.com/kubernetes-sigs/gateway-api/pull/2997"
spec:
  group: gateway.networking.k8s.io
  scope: Namespaced
  names:
    plural: referencegrants
    singular: referencegrant
    shortNames:
    - refgrant
    kind: ReferenceGrant
    categories:
    - gateway-api
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        description: |
          ReferenceGrant identifies kinds of resources in other namespaces that are 
          trusted to reference the specified kinds of resources in the same namespace 
          as the policy.
          
          Each ReferenceGrant can be used to represent a unique trust relationship.
          Additional Reference Grants can be used to add to the set of trusted sources
          of inbound references for the namespace they are defined within.
        type: object
        required:
        - spec
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object.'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents.'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of ReferenceGrant.
            type: object
            required:
            - from
            - to
            properties:
              from:
                description: |
                  From describes the trusted namespaces and kinds that can reference the 
                  resources described in "To". Each entry in this list must be considered 
                  to be an additional place that references can be valid from, or to put 
                  this another way, entries must be combined using OR.
                type: array
                maxItems: 16
                minItems: 1
                items:
                  description: ReferenceGrantFrom describes trusted namespaces and kinds.
                  type: object
                  required:
                  - group
                  - kind
                  - namespace
                  properties:
                    group:
                      description: |
                        Group is the group of the referent.
                        When empty, the Kubernetes core API group is inferred.
                        
                        Support: Core
                      type: string
                      maxLength: 253
                    kind:
                      description: |
                        Kind is the kind of the referent. Although implementations may support 
                        additional resources, the following types are part of the "Core" 
                        support level for this field:
                        
                        * Gateway (when used to permit a SecretObjectReference)
                        * HTTPRoute
                        * TCPRoute
                        * TLSRoute
                        * UDPRoute
                      type: string
                      maxLength: 63
                      minLength: 1
                      pattern: ^[a-zA-Z]([-a-zA-Z0-9]*[a-zA-Z0-9])?$
                    namespace:
                      description: |
                        Namespace is the namespace of the referent.
                        
                        Support: Core
                      type: string
                      maxLength: 63
                      minLength: 1
                      pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
              to:
                description: |
                  To describes the resources that may be referenced by the resources 
                  described in "From". Each entry in this list must be considered to be an 
                  additional place that references can be valid to, or to put this another 
                  way, entries must be combined using OR.
                type: array
                maxItems: 16
                minItems: 1
                items:
                  description: ReferenceGrantTo describes what Kinds are allowed as targets of the references.
                  type: object
                  required:
                  - group
                  - kind
                  properties:
                    group:
                      description: |
                        Group is the group of the referent.
                        When empty, the Kubernetes core API group is inferred.
                        
                        Support: Core
                      type: string
                      maxLength: 253
                    kind:
                      description: |
                        Kind is the kind of the referent. Although implementations may support 
                        additional resources, the following types are part of the "Core" 
                        support level for this field:
                        
                        * Secret (when used to permit a SecretObjectReference)
                        * Service
                      type: string
                      maxLength: 63
                      minLength: 1
                      pattern: ^[a-zA-Z]([-a-zA-Z0-9]*[a-zA-Z0-9])?$
                    name:
                      description: |
                        Name is the name of the referent. When unspecified or empty, this policy 
                        refers to all resources of the specified Group and Kind in the local 
                        namespace.
                      type: string
                      maxLength: 253
                      minLength: 1
    additionalPrinterColumns:
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp

