apiVersion: v1
kind: Namespace
metadata:
  name: edgion-system
  labels:
    name: edgion-system
    app.kubernetes.io/name: edgion
    app.kubernetes.io/component: system
---
apiVersion: v1
kind: Namespace
metadata:
  name: edgion-default
  labels:
    name: edgion-default
    app.kubernetes.io/name: edgion
    app.kubernetes.io/component: test
---
apiVersion: v1
kind: Namespace
metadata:
  name: edgion-test
  labels:
    name: edgion-test
    app.kubernetes.io/name: edgion
    app.kubernetes.io/component: test
---
apiVersion: v1
kind: Namespace
metadata:
  name: edgion-backend
  labels:
    name: edgion-backend
    app.kubernetes.io/name: edgion
    app.kubernetes.io/component: test
