apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: test-grpc
  namespace: edgion-test
spec:
  parentRefs:
    - name: grpc-test-gateway
      namespace: edgion-test
      sectionName: grpc

  hostnames:
    - "grpc.example.com"

  rules:
    # 1:  test.TestService 
    - matches:
        - method:
            type: Exact
            service: test.TestService
      backendRefs:
        - name: test-grpc
          port: 30021

    # 2:  test.TestService.SayHello 
    - matches:
        - method:
            type: Exact
            service: test.TestService
            method: SayHello
      backendRefs:
        - name: test-grpc
          port: 30021

