// gRPC TLS Test suite
// Test gRPC over HTTPS (TLS)
//
// Required config files (in examples/conf/):
// - EndpointSlice_edge_test-grpc.yaml         # gRPC backend service discovery
// - Service_edge_test-grpc.yaml               # gRPC service definition
// - GRPCRoute_edge_test-grpc-https.yaml       # gRPC TLS routing rules（Host: grpc-tls.test.example.com）
// - Gateway_edge_tls-terminate-gateway.yaml   # TLS termination Gateway config (listening port）
// - EdgionTls_edge_edge-tls.yaml              # TLS certificate config
// - Secret_edgion-test_edge-tls.yaml          # TLS certificate Secret
// - GatewayClass__public-gateway.yaml         # GatewayClass config
//
// Generated certificate files:
// - examples/testing/certs/server.crt         # server certificate (generated by generate_certs.sh)
// - examples/testing/certs/server.key         # server private key
// - examples/testing/certs/ca.pem             # CA certificate

use crate::framework::{TestCase, TestContext, TestResult, TestSuite};
use async_trait::async_trait;
use std::time::Instant;

// Use proto module from grpc_route
use crate::suites::grpc_route::test::test_service_client::TestServiceClient;
use crate::suites::grpc_route::test::HelloRequest;
use tonic::transport::{Certificate, Channel, ClientTlsConfig};

pub struct GrpcTlsTestSuite;

impl GrpcTlsTestSuite {
    /// Test gRPC over TLS SayHello RPC
    fn test_grpc_tls_say_hello() -> TestCase {
        TestCase::new("grpc_tls_say_hello", "gRPC TLS SayHello test", |ctx: TestContext| {
            Box::pin(async move {
                let start = Instant::now();

                // Build HTTPS connection URL
                let grpc_url = format!("https://{}:{}", ctx.target_host, ctx.grpc_https_port);

                // Read CA certificate
                let ca_pem = match std::fs::read_to_string("examples/test/certs/ca.pem") {
                    Ok(pem) => pem,
                    Err(e) => {
                        return TestResult::failed(start.elapsed(), format!("Failed to read CA certificate: {}", e));
                    }
                };

                let ca = Certificate::from_pem(ca_pem);

                // config TLS -  CA certificate domain_name
                let domain_name = ctx.grpc_host.as_deref().unwrap_or("localhost");
                let tls = ClientTlsConfig::new().ca_certificate(ca).domain_name(domain_name);

                // Create Channel
                let channel = match Channel::from_shared(grpc_url.clone()) {
                    Ok(mut endpoint) => {
                        // Gateway Mode: set origin to control :authority pseudo-header
                        if let Some(ref host) = ctx.grpc_host {
                            let origin_uri = match format!("https://{}:{}", host, ctx.grpc_https_port).parse() {
                                Ok(uri) => uri,
                                Err(e) => {
                                    return TestResult::failed(start.elapsed(), format!("Invalid origin URI: {}", e));
                                }
                            };
                            endpoint = endpoint.origin(origin_uri);
                        }

                        match endpoint.tls_config(tls) {
                            Ok(ep) => match ep.connect().await {
                                Ok(ch) => ch,
                                Err(e) => {
                                    return TestResult::failed(
                                        start.elapsed(),
                                        format!("Failed to connect to {}: {}", grpc_url, e),
                                    );
                                }
                            },
                            Err(e) => {
                                return TestResult::failed(start.elapsed(), format!("Failed to configure TLS: {}", e));
                            }
                        }
                    }
                    Err(e) => {
                        return TestResult::failed(start.elapsed(), format!("Invalid endpoint: {}", e));
                    }
                };

                let mut client = TestServiceClient::new(channel);

                // Create request - same as grpc_suite
                let request = tonic::Request::new(HelloRequest {
                    name: "Edgion".to_string(),
                });

                match client.say_hello(request).await {
                    Ok(response) => {
                        let reply = response.into_inner();
                        if reply.message.contains("Hello, Edgion!") {
                            let msg = if ctx.grpc_host.is_some() {
                                format!("Response: {}", reply.message)
                            } else {
                                format!("Response: {}, Server: {}", reply.message, reply.server_addr)
                            };
                            TestResult::passed_with_message(start.elapsed(), msg)
                        } else {
                            TestResult::failed(start.elapsed(), format!("Unexpected response: {}", reply.message))
                        }
                    }
                    Err(e) => TestResult::failed(
                        start.elapsed(),
                        format!("RPC failed: {} (status: {:?})", e.message(), e.code()),
                    ),
                }
            })
        })
    }
}

#[async_trait]
impl TestSuite for GrpcTlsTestSuite {
    fn name(&self) -> &str {
        "gRPC-TLS"
    }

    fn test_cases(&self) -> Vec<TestCase> {
        vec![Self::test_grpc_tls_say_hello()]
    }
}
