// HTTPS Test suite
// Only tested in Gateway mode，uses /secure/ path prefix
//
// Required config files (in examples/conf/):
// - EndpointSlice_edge_test-http.yaml         # HTTPS backend service (reuse HTTP backend)
// - Service_edge_test-http.yaml               # HTTPS service definition
// - HTTPRoute_edge_test-http.yaml             # HTTPS routing rules（Host: test.example.com, path: /secure/）
// - Gateway_edge_tls-terminate-gateway.yaml   # TLS termination Gateway config (listening port）
// - EdgionTls_edge_edge-tls.yaml              # TLS certificate config
// - Secret_edgion-test_edge-tls.yaml          # TLS certificate Secret
// - GatewayClass__public-gateway.yaml         # GatewayClass config
//
// Generated certificate files:
// - examples/testing/certs/server.crt         # server certificate (generated by generate_certs.sh)
// - examples/testing/certs/server.key         # server private key
// - examples/testing/certs/ca.pem             # CA certificate

use crate::framework::{TestCase, TestContext, TestResult, TestSuite};
use async_trait::async_trait;
use std::time::Instant;

pub struct HttpsTestSuite;

impl HttpsTestSuite {
    fn test_https_secure_health() -> TestCase {
        TestCase::new(
            "https_secure_health",
            "Test HTTPS /secure/health endpoint",
            |ctx: TestContext| {
                Box::pin(async move {
                    let start = Instant::now();

                    // Build HTTPS URL - use http_host for proper SNI in Gateway mode
                    let host = ctx.http_host.as_deref().unwrap_or(&ctx.target_host);
                    let url = format!("https://{}:{}/secure/health", host, ctx.https_port);

                    let request = ctx.http_client.get(&url);

                    match request.send().await {
                        Ok(response) => {
                            let status = response.status();
                            match response.text().await {
                                Ok(body) => {
                                    // Test server returns request info at /secure/health
                                    // Accept both "healthy" and path info as success indicators
                                    if status.is_success() && (body.contains("healthy") || body.contains("Path: /secure/health")) {
                                        TestResult::passed_with_message(
                                            start.elapsed(),
                                            format!("Status: {}", status),
                                        )
                                    } else {
                                        TestResult::failed(
                                            start.elapsed(),
                                            format!("Unexpected response. Status: {}, Body: {}", status, body),
                                        )
                                    }
                                }
                                Err(e) => {
                                    TestResult::failed(start.elapsed(), format!("Failed to read response body: {}", e))
                                }
                            }
                        }
                        Err(e) => TestResult::failed(start.elapsed(), format!("HTTPS request failed: {}", e)),
                    }
                })
            },
        )
    }

    fn test_https_secure_echo() -> TestCase {
        TestCase::new(
            "https_secure_echo",
            "Test HTTPS /secure/echo endpoint（GET request）",
            |ctx: TestContext| {
                Box::pin(async move {
                    let start = Instant::now();

                    // Use http_host for proper SNI in Gateway mode
                    let host = ctx.http_host.as_deref().unwrap_or(&ctx.target_host);
                    let url = format!("https://{}:{}/secure/echo", host, ctx.https_port);

                    // Use GET request as test server returns request info
                    let request = ctx.http_client.get(&url);

                    match request.send().await {
                        Ok(response) => {
                            let status = response.status();
                            if status.is_success() {
                                TestResult::passed_with_message(
                                    start.elapsed(),
                                    format!("Status: {}", status),
                                )
                            } else {
                                match response.text().await {
                                    Ok(body) => {
                                        TestResult::failed(
                                            start.elapsed(),
                                            format!("Request failed. Status: {}, Body: {}", status, body),
                                        )
                                    }
                                    Err(e) => {
                                        TestResult::failed(
                                            start.elapsed(),
                                            format!("Request failed. Status: {}, Error reading body: {}", status, e),
                                        )
                                    }
                                }
                            }
                        }
                        Err(e) => TestResult::failed(start.elapsed(), format!("HTTPS request failed: {}", e)),
                    }
                })
            },
        )
    }

    fn test_https_secure_status() -> TestCase {
        TestCase::new(
            "https_secure_status",
            "Test HTTPS /secure/status/200 endpoint",
            |ctx: TestContext| {
                Box::pin(async move {
                    let start = Instant::now();

                    // Use http_host for proper SNI in Gateway mode
                    let host = ctx.http_host.as_deref().unwrap_or(&ctx.target_host);
                    let url = format!("https://{}:{}/secure/status/200", host, ctx.https_port);

                    let request = ctx.http_client.get(&url);

                    match request.send().await {
                        Ok(response) => {
                            let status = response.status();
                            if status.as_u16() == 200 {
                                TestResult::passed_with_message(start.elapsed(), format!("Status code: {}", status))
                            } else {
                                TestResult::failed(start.elapsed(), format!("Expected 200, got {}", status))
                            }
                        }
                        Err(e) => TestResult::failed(start.elapsed(), format!("HTTPS request failed: {}", e)),
                    }
                })
            },
        )
    }
}

#[async_trait]
impl TestSuite for HttpsTestSuite {
    fn name(&self) -> &str {
        "HTTPS"
    }

    fn test_cases(&self) -> Vec<TestCase> {
        vec![
            Self::test_https_secure_health(),
            Self::test_https_secure_echo(),
            Self::test_https_secure_status(),
        ]
    }
}
