---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: edgion-controller
  namespace: edgion-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edgion-controller
rules:
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["gatewayclasses", "gateways", "httproutes", "grpcroutes", "tcproutes", "udproutes", "tlsroutes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["gatewayclasses/status", "gateways/status", "httproutes/status", "grpcroutes/status", "tcproutes/status", "udproutes/status", "tlsroutes/status"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["backendtlspolicies"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["backendtlspolicies/status"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["discovery.k8s.io"]
  resources: ["endpointslices"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["edgion.io"]
  resources: ["edgiontls", "edgiongatewayclassconfigs", "edgionstreamplugins", "edgionplugins", "pluginmetadata", "linksys", "edgionacmes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["edgion.io"]
  resources: ["edgiontls/status", "edgiongatewayclassconfigs/status", "edgionstreamplugins/status", "edgionplugins/status", "edgionacmes/status"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["referencegrants"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: edgion-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edgion-controller
subjects:
- kind: ServiceAccount
  name: edgion-controller
  namespace: edgion-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: edgion-controller-pod-label
  namespace: edgion-system
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: edgion-controller-pod-label
  namespace: edgion-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: edgion-controller-pod-label
subjects:
- kind: ServiceAccount
  name: edgion-controller
  namespace: edgion-system
