apiVersion: v1
kind: Service
metadata:
  name: edgion-controller
  namespace: edgion-system
  labels:
    app: edgion-controller
spec:
  type: ClusterIP
  selector:
    app: edgion-controller
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
    protocol: TCP
  - name: http
    port: 5800
    targetPort: 5800
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: edgion-controller-leader
  namespace: edgion-system
  labels:
    app: edgion-controller
spec:
  type: ClusterIP
  selector:
    app: edgion-controller
    edgion.io/leader: "true"
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
    protocol: TCP
  - name: http
    port: 5800
    targetPort: 5800
    protocol: TCP
