apiVersion: edgion.io/v1
kind: LinkSys
metadata:
  name: simple-redis
  namespace: default
spec:
  type: redis
  config:
    endpoints:
      - "redis://localhost:6379"
    auth:
      password: "mypassword"
    topology:
      mode: standalone

