apiVersion: v1
kind: Service
metadata:
  name: grpc-service-backup
  namespace: test1
spec:
  ports:
    - name: grpc-30023
      port: 30023
      protocol: TCP
      targetPort: 30023
    - name: grpc-30024
      port: 30024
      protocol: TCP
      targetPort: 30024
  type: ClusterIP

