apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: tcp-route1
  namespace: test1
spec:
  parentRefs:
    - name: gateway1
      namespace: default
      sectionName: tcp19000
  rules:
    - backendRefs:
        - name: aaa-service
          namespace: test1
          port: 30001
          weight: 100

