apiVersion: v1
kind: Service
metadata:
  name: aaa-service
  namespace: test4
spec:
  ports:
    - name: http-30001
      port: 30001
      protocol: TCP
      targetPort: 30001
    - name: http-30002
      port: 30002
      protocol: TCP
      targetPort: 30002
  type: ClusterIP
