apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: example-udp-route
  namespace: default
spec:
  parentRefs:
    - name: gateway1
      namespace: default
      sectionName: udp19001
      port: 19001  # Must match Gateway listener port
  rules:
    - backendRefs:
        - name: udp-service
          namespace: default
          port: 5353
          weight: 1

