apiVersion: edgion.io/v1
kind: EdgionPlugins
metadata:
  name: ldap-auth-anonymous
  namespace: edgion-default
spec:
  requestPlugins:
    - enable: true
      type: LdapAuth
      config:
        ldapHost: "edgion-test-openldap.edgion-test.svc.cluster.local"
        ldapPort: 389
        baseDn: "ou=people,dc=example,dc=org"
        attribute: "uid"
        headerType: "ldap"
        anonymous: "guest-user"
        hideCredentials: true
        timeout: 3000
