# EdgionTls HTTPS  Gateway
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: edgiontls-https-gateway
  namespace: edgion-test
spec:
  gatewayClassName: public-gateway
  listeners:
    # HTTPS  -  EdgionTls  TLS
    - name: https
      protocol: HTTPS
      port: 31190
