apiVersion: edgion.io/v1
kind: EdgionPlugins
metadata:
  name: https-redirect-plugin
  namespace: default
spec:
  plugins:
    - enable: true
      type: requestRedirect
      config:
        scheme: https
        statusCode: 301

