apiVersion: edgion.io/v1
kind: EdgionTls
metadata:
  name: edge-tls
  namespace: edgion-test
spec:
  parentRefs:
    - name: example-gateway
      namespace: edgion-test
  hosts:
    - test.example.com
    - grpc.example.com
  secretRef:
    name: edge-tls
    namespace: edgion-test

