apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: mtls-test-gateway
  namespace: edge
spec:
  gatewayClassName: public-gateway
  listeners:
    - name: https-mtls
      protocol: HTTPS
      port: 10444

