apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend-tls-test
  namespace: edge
spec:
  parentRefs:
    - name: example-gateway
      namespace: edge
  hostnames:
    - "test.example.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /backend-tls/
      filters:
        - type: ExtensionRef
          extensionRef:
            group: gateway.edgion.io
            kind: DebugAccessLogToHeader
            name: debug-backend-tls
      backendRefs:
        - name: test-backend-tls
          port: 30051

