apiVersion: v1
kind: Service
metadata:
  name: backend-b
  namespace: edge
spec:
  ports:
    - name: http
      port: 30001
      protocol: TCP
      targetPort: 30001
  selector:
    app: test-http

