apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: test-tcp-filtered
  namespace: edge
  annotations:
    # Reference EdgionStreamPlugins using annotation
    edgion.io/stream-plugins: test-ip-filter
spec:
  parentRefs:
    - name: example-gateway
      namespace: edge
      sectionName: tcp-filtered
  rules:
    - backendRefs:
        - name: test-tcp
          port: 30010
          weight: 100

