apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: test-tls-tcp
  namespace: edge
spec:
  parentRefs:
    - name: tls-terminate-gateway
      namespace: edge
      sectionName: tls-terminate-tcp
  hostnames:
    - "tcp.example.com"  # SNI hostname
  rules:
    - backendRefs:
        - name: test-tcp
          port: 30010

