// Gateway TLS Test suite
// Test TLS certificate configured directly on Gateway Listener via certificateRefs
//
// Test scenario:
// - Client → Gateway: HTTPS (port 31220, TLS certificate from Gateway.spec.listeners[].tls.certificateRefs)
// - Gateway → Backend: HTTP (port 30001)
//
// This is different from EdgionTls:
// - EdgionTls: TLS config via EdgionTls CRD
// - Gateway TLS: TLS config directly on Gateway Listener (Kubernetes Gateway API standard)
//
// Required config files:
// - Gateway/TLS/GatewayTLS/Gateway.yaml     # Gateway with tls.certificateRefs
// - Gateway/TLS/GatewayTLS/HTTPRoute.yaml   # Simple route for testing
// - base/Secret_edgion-test_edge-tls.yaml   # TLS certificate Secret (generated by generate_tls_certs.sh)

use crate::framework::{TestCase, TestContext, TestResult, TestSuite};
use async_trait::async_trait;
use std::time::Instant;

pub struct GatewayTlsTestSuite;

impl GatewayTlsTestSuite {
    fn test_gateway_tls_health() -> TestCase {
        TestCase::new(
            "gateway_tls_health",
            "Test Gateway TLS - HTTPS /health endpoint",
            |ctx: TestContext| {
                Box::pin(async move {
                    let start = Instant::now();

                    // Use http_host for proper SNI (gateway-tls.example.com)
                    let host = ctx.http_host.as_deref().unwrap_or(&ctx.target_host);
                    let url = format!("https://{}:{}/health", host, ctx.https_port);

                    let request = ctx.http_client.get(&url);

                    match request.send().await {
                        Ok(response) => {
                            let status = response.status();
                            match response.text().await {
                                Ok(body) => {
                                    if status.is_success() {
                                        TestResult::passed_with_message(
                                            start.elapsed(),
                                            format!("Gateway TLS works! Status: {}, Body length: {}", status, body.len()),
                                        )
                                    } else {
                                        TestResult::failed(
                                            start.elapsed(),
                                            format!("Unexpected response. Status: {}, Body: {}", status, body),
                                        )
                                    }
                                }
                                Err(e) => {
                                    TestResult::failed(start.elapsed(), format!("Failed to read response body: {}", e))
                                }
                            }
                        }
                        Err(e) => TestResult::failed(start.elapsed(), format!("Gateway TLS request failed: {}", e)),
                    }
                })
            },
        )
    }

    fn test_gateway_tls_echo() -> TestCase {
        TestCase::new(
            "gateway_tls_echo",
            "Test Gateway TLS - HTTPS /echo endpoint",
            |ctx: TestContext| {
                Box::pin(async move {
                    let start = Instant::now();

                    let host = ctx.http_host.as_deref().unwrap_or(&ctx.target_host);
                    let url = format!("https://{}:{}/echo", host, ctx.https_port);

                    let request = ctx.http_client.get(&url).header("X-Test-Gateway-TLS", "true");

                    match request.send().await {
                        Ok(response) => {
                            let status = response.status();
                            match response.text().await {
                                Ok(body) => {
                                    // Verify the custom header is forwarded
                                    if status.is_success() && body.contains("X-Test-Gateway-TLS") {
                                        TestResult::passed_with_message(
                                            start.elapsed(),
                                            "Request forwarded correctly through Gateway TLS".to_string(),
                                        )
                                    } else if status.is_success() {
                                        // Even if header not in response, TLS worked
                                        TestResult::passed_with_message(
                                            start.elapsed(),
                                            format!("Gateway TLS echo works. Status: {}", status),
                                        )
                                    } else {
                                        TestResult::failed(
                                            start.elapsed(),
                                            format!("Echo failed. Status: {}, Body: {}", status, body),
                                        )
                                    }
                                }
                                Err(e) => {
                                    TestResult::failed(start.elapsed(), format!("Failed to read response body: {}", e))
                                }
                            }
                        }
                        Err(e) => TestResult::failed(start.elapsed(), format!("Gateway TLS echo request failed: {}", e)),
                    }
                })
            },
        )
    }

    fn test_gateway_tls_status() -> TestCase {
        TestCase::new(
            "gateway_tls_status",
            "Test Gateway TLS - HTTPS /status/200 endpoint",
            |ctx: TestContext| {
                Box::pin(async move {
                    let start = Instant::now();

                    let host = ctx.http_host.as_deref().unwrap_or(&ctx.target_host);
                    let url = format!("https://{}:{}/status/200", host, ctx.https_port);

                    let request = ctx.http_client.get(&url);

                    match request.send().await {
                        Ok(response) => {
                            let status = response.status();
                            if status.as_u16() == 200 {
                                TestResult::passed_with_message(
                                    start.elapsed(),
                                    format!("Gateway TLS status test passed. Status: {}", status),
                                )
                            } else {
                                TestResult::failed(start.elapsed(), format!("Expected 200, got {}", status))
                            }
                        }
                        Err(e) => TestResult::failed(start.elapsed(), format!("Gateway TLS status request failed: {}", e)),
                    }
                })
            },
        )
    }
}

#[async_trait]
impl TestSuite for GatewayTlsTestSuite {
    fn name(&self) -> &str {
        "gateway_tls"
    }

    fn test_cases(&self) -> Vec<TestCase> {
        vec![
            Self::test_gateway_tls_health(),
            Self::test_gateway_tls_echo(),
            Self::test_gateway_tls_status(),
        ]
    }
}
